In [3]:
import numpy as np
import time
import random

# 第十四章 动态规划

将大问题分成小问题后，会出现相互重叠的部分，这是用递归就会很复杂，因此考虑用动态规划进行运算

## Q88：爬楼梯的最少成本

In [2]:
l0 = [1,100,1,1,100,1]

### 用递归的方法解决(回溯法)

In [19]:
def cal_min_cost(l,i=0,cost0=0):
    #print(i,cost0,min_cost)
    if i >= len(l)-2:
        return l[i]
    elif i < len(l)-2:
        cost0 = l[i]
        f_i1 = cal_min_cost(l,i+1)
        f_i2 = cal_min_cost(l,i+2)
        return cost0+min(f_i1,f_i2)

In [20]:
cal_min_cost([0]+l0)

4

### 用缓存的递归方法解决（用dp存储每一步的解）

In [29]:
def cal_min_cost(l):
    l = l+[0]
    dp = [None for i in range(len(l))]
    dp[0] = l[0]
    dp[1] = l[1]
    for i in range(2,len(l)):
        dp[i] = min(dp[i-1],dp[i-2])+l[i]
    return dp[-1]
cal_min_cost(l0)

4

### 用缓存的递归方法解决（用dp存储每一步的解,且只保留上一步和上上步的dp）

In [30]:
def cal_min_cost(l):
    l = l+[0]
    dp = [None for i in range(len(l))]
    dp[0] = l[0]
    dp[1] = l[1]
    for i in range(2,len(l)):
        dp[i%2] = min(dp[0],dp[1])+l[i]
    return dp[i%2]
cal_min_cost(l0)

4

## 单序列问题

### Q89:房屋被盗

In [32]:
def theft(l):
    dp = [None for i in range(2)]
    dp[0] = l[0]
    dp[1] = max(l[0],l[1])
    for i in range(2,len(l)):
        dp[i%2] = max(dp[(i-1)%2],dp[i%2]+l[i])
    return dp[i%2]
l = [2,3,4,5,3]
theft(l)

9

**用两个状态转移方程去求解**

In [33]:
def theft(l):
    #未进入房屋偷盗
    f = [None for i in range(2)]
    #进入房屋偷盗
    g = [None for i in range(2)]
    f[0] = 0
    g[0] = l[0]
    f[1] = g[0]
    g[1] = l[1]
    for i in range(2,len(l)):
        g[i%2] = g[i%2]+l[i]
        f[i%2] = f[(i-1)%2]
    return max(g[i%2],f[i%2])
l = [2,3,4,5,3]
theft(l)

9

### Q90:环形房屋偷盗

In [34]:
max(theft(l[:-1]),theft(l[1:]))

8

### Q91:粉刷房子

In [36]:
#n 房子的个数
#k color的个数
def print_house(l):
    dp1 = [None for i in range(2)]
    dp2 = [None for i in range(2)]
    dp3 = [None for i in range(2)]
    dp1[1],dp2[1],dp3[1] = l[0][0],l[0][1],l[0][2]
    dp1[0],dp2[0],dp3[0] = min(dp2[1],dp3[1]),min(dp1[1],dp3[1]),min(dp1[1],dp2[1])
    for i in range(1,len(l)):
        dp1[1] = dp1[0]+l[i][0]
        dp2[1] = dp2[0]+l[i][1]
        dp3[1] = dp3[0]+l[i][2]
        dp1[0],dp2[0],dp3[0] = min(dp2[1],dp3[1]),min(dp1[1],dp3[1]),min(dp1[1],dp2[1])
    return min(dp1[1],dp2[1],dp3[1])
house = [[17,2,16],[15,14,5],[13,3,1]]
print_house(house)

10

### Q92:翻转字符

In [42]:
s0 = '00110'
def fanzhuan(s0):
    dp = [None,None]
    if s0[0] == '0':
        dp[0] = 0
        dp[1] = 1
    else:
        dp[1] = 0
        dp[0] = 1
    for i in range(1,len(s0)):       
        if s0[i] == '0':
            dp[0] = dp[0]
            dp[1] = min(dp[0]+1,dp[1]+1)          
        else:
            dp[1] = min(dp[0],dp[1])
            dp[0] = dp[0]+1
    return min(dp[0],dp[1])
fanzhuan(s0)          

1

### Q93:最长的斐波那契数列

In [10]:
l = [1,2,3,4,5,6,7,8]
def cal_max_num(l):
    dp = np.zeros(shape=(len(l),len(l)),dtype=int)
    A = {}
    for i in range(len(l)):
        A[l[i]] = i
    maxp = 0
    for i in range(1,len(l)):
        for j in range(i):
            k = l[i]-l[j]
            if A.get(k,-1) >= 0 and A[k] < j:
                dp[i][j] = dp[j][A[k]] + 1
            else:
                dp[i][j] = 2
            maxp = max(maxp,dp[i][j])
            #print(i,j,dp[i][j])
    return maxp
cal_max_num(l)

5

### Q94:最少回文分割

In [13]:
def is_hui_wen(s,ind1,ind2):
    p1 = ind1
    p2 = ind2
    flag = 0
    while p1 <= p2:
        if s[p1]!= s[p2]:
            flag = 1
            break
        else:
            p1 += 1
            p2 -= 1
    if flag == 0:
        return True
    else:
        return False
def min_huiwen_split(s):
    dp = [i for i in range(len(s))]
    for i in range(len(s)):
        for j in range(i):
            if is_hui_wen(s,j,i):
                if j == 0:
                    dp[i] = 0
                else:
                    dp[i] = min(dp[i],dp[j-1]+1)
    return dp[-1]
min_huiwen_split('aaba')

1

## 双序列问题

### Q95：最长公共子序列

In [16]:
def max_mutil_s(s1,s2):
    len1 = len(s1)
    len2 = len(s2)
    dp = np.zeros(shape=(len1,len2),dtype=int)
    for i in range(len1):
        for j in range(len2):
            if s1[i] == s2[j]:
                if i > 0 and j > 0:
                    dp[i][j] = dp[i-1][j-1]+1
                else:
                    dp[i][j] = 1
            else:
                if i > 0 and j > 0:
                    dp[i][j] = max(dp[i][j-1],dp[i-1][j])
                else:
                    dp[i][j] = 0
    return dp[-1][-1]
                
max_mutil_s('abcde','badfe')

3

### Q96:字符串交织

In [41]:
def is_jiaozhi(s0,s1,s2):
    len0 = len(s0)
    len1 = len(s1)
    len2 = len(s2)
    dp = np.zeros(shape=(len0+1,len1+1,len2+1))
    flag = 0
    s1 = ' '+s1
    s2 = ' '+s2
    for i in range(len0):
        for j in range(len1+1):
            for k in range(len2+1):
                if s0[i] == s1[j]:
                    dp[i+1][j][k] = dp[i][j-1][k]+1
                if s0[i] == s2[k]:
                    dp[i+1][j][k] = dp[i][j][k-1]+1
                if s0[i] != s1[j] and s0[i] != s2[k]: 
                    if j > 0 and k > 0:
                        dp[i+1][j][k] = max(dp[i][j][k],dp[i+1][j-1][k],dp[i+1][j][k-1])
                    elif j > 0 and k == 0:
                        dp[i+1][j][k] = max(dp[i][j][k],dp[i+1][j-1][k])
                    elif k > 0 and j == 0:
                        dp[i+1][j][k] = max(dp[i][j][k],dp[i+1][j][k-1])
        print(dp[i+1])       
        if dp[i+1][-1][-1] < i+1:
            flag = 1
            break
    if flag == 1:
        return False
    else:
        return True
is_jiaozhi('cgdkemnf','cdef','gkmn')   

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 1. 1. 1. 1.]
 [1. 2. 2. 2. 2.]
 [1. 2. 2. 2. 2.]
 [1. 2. 2. 2. 2.]
 [1. 2. 2. 2. 2.]]
[[0. 1. 1. 1. 1.]
 [1. 2. 2. 2. 2.]
 [2. 3. 3. 3. 3.]
 [2. 3. 3. 3. 3.]
 [2. 3. 3. 3. 3.]]
[[0. 1. 2. 2. 2.]
 [1. 2. 3. 3. 3.]
 [2. 3. 4. 4. 4.]
 [2. 3. 4. 4. 4.]
 [2. 3. 4. 4. 4.]]
[[0. 1. 2. 2. 2.]
 [1. 2. 3. 3. 3.]
 [2. 3. 4. 4. 4.]
 [3. 4. 5. 5. 5.]
 [3. 4. 5. 5. 5.]]
[[0. 1. 2. 3. 3.]
 [1. 2. 3. 4. 4.]
 [2. 3. 4. 5. 5.]
 [3. 4. 5. 6. 6.]
 [3. 4. 5. 6. 6.]]
[[0. 1. 2. 3. 4.]
 [1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]
 [3. 4. 5. 6. 7.]
 [3. 4. 5. 6. 7.]]
[[0. 1. 2. 3. 4.]
 [1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]
 [3. 4. 5. 6. 7.]
 [4. 5. 6. 7. 8.]]


True

### Q97：子序列的数目

In [43]:
def have_xulie_num(s,t):
    len_s = len(s)
    len_t = len(t)
    dp = np.zeros(shape=(len_s+1,len_t+1),dtype=int)
    dp[0][0] = 1
    for i in range(1,len_s+1):
        dp[i][0] = 1
        for j in range(1,min(i+1,len_t+1)):
            if s[i-1] == t[j-1]:
                dp[i][j] = dp[i-1][j-1]+dp[i-1][j]
            else:
                dp[i][j] = dp[i-1][j]
    return dp[-1][-1]
have_xulie_num('appplep','apple')      

3

## 矩阵问题

### Q98:路径的数目

In [46]:
def cal_road_num(m,n):
    if m==1 or n==1:
        return 1
    elif m > 1 and n > 1:
        return cal_road_num(m-1,n)+cal_road_num(m,n-1)
cal_road_num(3,3)

6

### Q99:最小路径之和

In [56]:
def f0(a,m,n):
    if m==1 and n > 1:
        return a[m-1][n-1]+f0(a,m,n-1)
    elif n==1 and m>1:
        return a[m-1][n-1]+f0(a,m-1,n)
    elif m==1 and n==1:
        return a[m-1][n-1]
    else:
        return min(f0(a,m-1,n),f0(a,m,n-1))+a[m-1][n-1]
f0([[1,3,1],[2,5,2],[3,4,1]],3,3)

8

## 背包问题

### Q101:分割等和子集

In [66]:
def canPatition(l):
    sum0 = 0
    for i in l:
        sum0 += i
    if sum0%2 == 0:
        dp = [{0:True} for i in range(len(l)+1)]
        return subsetSum(l,ind=len(l),target=sum0//2,dp=dp)
def subsetSum(l,ind,target,dp):
    if ind == 0 and target > 0:
        dp[ind][target] = False
        print(ind,target,dp)
        return dp[ind][target]
    elif target == 0:
        print(ind,target,dp)
        return dp[ind][target]
    else:
        dp[ind][target] = subsetSum(l,ind-1,target,dp)
        if dp[ind][target] == False and target-l[ind-1] >= 0:
            dp[ind][target] = subsetSum(l,ind-1,target-l[ind-1],dp)
        print(ind,target,dp)
        return dp[ind][target]
canPatition([3,4,1])     

0 4 [{0: True, 4: False}, {0: True}, {0: True}, {0: True}]
0 1 [{0: True, 4: False, 1: False}, {0: True, 4: False}, {0: True}, {0: True}]
1 4 [{0: True, 4: False, 1: False}, {0: True, 4: False}, {0: True}, {0: True}]
1 0 [{0: True, 4: False, 1: False}, {0: True, 4: False}, {0: True, 4: False}, {0: True}]
2 4 [{0: True, 4: False, 1: False}, {0: True, 4: False}, {0: True, 4: True}, {0: True}]
3 4 [{0: True, 4: False, 1: False}, {0: True, 4: False}, {0: True, 4: True}, {0: True, 4: True}]


True

### Q102:加减的目标值

In [67]:
def canPartition1(l,target):
    sum0 = 0
    for i in l:
        sum0 += i
    if (sum0+target)%2 == 0:
        dp = [{0:True} for i in range(len(l)+1)]
        return subsetSum(l,ind=len(l),target=(sum0+target)//2,dp=dp)
    else:
        return False
canPartition1([2,2,2],2)

0 4 [{0: True, 4: False}, {0: True}, {0: True}, {0: True}]
0 2 [{0: True, 4: False, 2: False}, {0: True, 4: False}, {0: True}, {0: True}]
1 4 [{0: True, 4: False, 2: False}, {0: True, 4: False}, {0: True}, {0: True}]
0 2 [{0: True, 4: False, 2: False}, {0: True, 4: False}, {0: True, 4: False}, {0: True}]
0 0 [{0: True, 4: False, 2: False}, {0: True, 4: False, 2: False}, {0: True, 4: False}, {0: True}]
1 2 [{0: True, 4: False, 2: False}, {0: True, 4: False, 2: True}, {0: True, 4: False}, {0: True}]
2 4 [{0: True, 4: False, 2: False}, {0: True, 4: False, 2: True}, {0: True, 4: True}, {0: True}]
3 4 [{0: True, 4: False, 2: False}, {0: True, 4: False, 2: True}, {0: True, 4: True}, {0: True, 4: True}]


True

### Q103:最少的硬币（无限背包问题）

In [5]:
def least_num(coins,target):
    ind = len(coins)
    dp = {}
    dp[0] = 0
    for i in range(1,target+1):#不能用硬币输出该面值硬币
        dp[i] = i+1
    for i in range(len(coins)):
        for j in range(target,0,-1):
            k = 0
            while j-k*coins[i] >= 0:
                #print(j,k,coins,i,dp)
                dp[j] = min(dp[j],dp[j-k*coins[i]]+k)
                k += 1
            #print(i,j,dp)
    if dp[target] > target:
        return None
    else:
        return dp[target]
least_num([1,3,9,10],15)

3

### Q104:排列的数目

In [12]:
def least_num(coins,target):
    ind = len(coins)
    dp = {}
    dp[0] = 1
    for i in range(1,target+1):
        dp[i] = 0
    for i in range(1,target+1):
        for coin in coins:
            if i >= coin:
                print(dp,i,coin)
                dp[i] += dp[i-coin]
    return dp[target]
least_num([1,2,3],3)

{0: 1, 1: 0, 2: 0, 3: 0} 1 1
{0: 1, 1: 1, 2: 0, 3: 0} 2 1
{0: 1, 1: 1, 2: 1, 3: 0} 2 2
{0: 1, 1: 1, 2: 2, 3: 0} 3 1
{0: 1, 1: 1, 2: 2, 3: 2} 3 2
{0: 1, 1: 1, 2: 2, 3: 3} 3 3


4