# 第二章 数组  
## 双指针

### Q8:求和大于或等于k的最短连续子数组（子数组的数均为正整数）

In [17]:
import numpy as np
import time
array = np.random.randint(0,8,100)
k = 12 
array

array([5, 6, 0, 6, 1, 5, 1, 2, 6, 0, 2, 7, 2, 1, 6, 2, 0, 4, 4, 7, 4, 7,
       6, 0, 0, 2, 1, 1, 3, 2, 5, 1, 2, 1, 1, 2, 7, 1, 6, 2, 5, 2, 7, 0,
       4, 5, 4, 4, 1, 0, 6, 7, 6, 3, 2, 7, 4, 4, 6, 0, 0, 4, 4, 6, 4, 6,
       4, 0, 4, 5, 7, 0, 3, 6, 0, 3, 3, 0, 3, 0, 5, 5, 6, 3, 7, 3, 2, 0,
       0, 0, 3, 1, 1, 4, 2, 3, 7, 7, 5, 6])

In [18]:
start = time.perf_counter()
n = len(array)
min_len = n
right = 0
left = 0
best_array = array
while right < n and right>=0 and left >= 0 and left <= right:
    if array[left:right+1].sum() >= k:
        min_len = min(min_len,right+1-left)
        if min_len == right+1-left:
            best_array = array[left:right+1]
        left += 1
    elif array[left:right+1].sum() < k:
        right += 1
print(best_array,min_len)
elapsed = time.perf_counter() - start
print('Time used:','%.6f ms'%(1000*elapsed))

[7 5] 2
Time used: 1.536200 ms


## 累加和求解
### Q10:求和为k的子数组的个数（数字不全为正整数）

In [34]:
array = np.random.randint(-8,8,100)
k = 0
#k = 12 
#k = 2
#array = [1,1,1,1]
array

array([ 6,  7,  0, -4, -4,  4, -7,  2,  4, -1, -5, -1, -2,  3, -2, -1,  5,
        6,  0,  6,  4, -6, -8,  6, -8, -6,  5,  6,  7,  5,  3, -2,  1, -6,
        6,  7, -4,  3, -8, -3, -5, -3,  4,  1,  6,  1, -1,  2,  7,  6,  4,
       -4, -6, -7, -3, -8,  3,  0, -4,  0,  2,  4, -3, -1,  1, -8,  0, -4,
       -6,  3, -2, -5, -5,  1, -5, -1,  0,  1, -8,  0,  0, -1, -7,  5, -5,
        2, -3,  1, -1,  4, -1, -2,  6, -6,  7,  0,  5, -6, -2,  4])

In [37]:
#不初始化键值对0:1
start = time.perf_counter()
n = len(array)
right = 0
sum_cum = 0
sum_dict = {}
count = 0
#k = 13
for right in range(n):
    sum_cum += array[right]
    sum_dict[sum_cum] = sum_dict.get(sum_cum,0)+1
    count += sum_dict.get(sum_cum-k,0)+(sum_cum==k)
print(count)
elapsed = time.perf_counter() - start
print('Time used:','%.6f ms'%(1000*elapsed))

190
Time used: 0.889000 ms


In [38]:
#初始化键值对0:1
start = time.perf_counter()
n = len(array)
right = 0
sum_cum = 0
sum_dict = {0:1}
count = 0
#k = 13
for right in range(n):
    sum_cum += array[right]
    sum_dict[sum_cum] = sum_dict.get(sum_cum,0)+1
    count += sum_dict.get(sum_cum-k,0)
print(count)
elapsed = time.perf_counter() - start
print('Time used:','%.6f ms'%(1000*elapsed))

190
Time used: 0.416800 ms


### Q11:0和1个数相同的最长子数组  
思路：用累加求解，将0变为-1

In [40]:
array = np.random.randint(0,2,100)

array([1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1])

In [51]:
start = time.perf_counter()
n = len(array)
right = 0
sum_cum = 0
k =0
sum_dict = {0:0}
max_len = 0
for right in range(n):
    sum_cum += 2*array[right]-1
    max_len = max(max_len,right-sum_dict.get(sum_cum-k,right+1)+1)
    #print(max_len,right)
    sum_dict[sum_cum] = min(sum_dict.get(sum_cum,n),right+1)
print(max_len)

52
